/**
 * Generates a human-readable review sheet of the whole question bank.
 *
 *   npm run review          -> writes docs/review-sheet.md
 *   npm run review -- new   -> only questions listed in docs/.review-seen is omitted
 *
 * Automated validation proves questions are well-formed and that the maths adds
 * up. It cannot tell you whether a question is *fair* — whether the wording is
 * clear, whether a distractor is accidentally arguable, or whether the reading
 * level is right. That needs a person, and this sheet is what they read.
 *
 * Questions are shown in the shuffled order the child actually sees, so the
 * sheet matches the real thing.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { shuffleOptions } from '../src/data/shuffle'

const here = dirname(fileURLToPath(import.meta.url))
const dataDir = join(here, '..', 'src', 'data')
const docsDir = join(here, '..', 'docs')
const seenFile = join(docsDir, '.review-seen')

const LETTERS = ['A', 'B', 'C', 'D', 'E', 'F']
const DIFFICULTY = ['', 'Foundation', 'Standard', 'Challenging', 'Stretch']

interface Question {
  id: string
  subject: string
  topic: string
  skill: string
  difficulty: number
  passageId?: string
  question: string
  options: string[]
  answer: number
  explanation: string
  distractorNotes?: string[]
  learningPoint: string
  verify?: string
}

const onlyNew = process.argv.includes('new')
const seen = new Set<string>(
  onlyNew && existsSync(seenFile)
    ? readFileSync(seenFile, 'utf8').split('\n').map((l) => l.trim()).filter(Boolean)
    : [],
)

const questions: Question[] = []
for (const file of readdirSync(dataDir).filter((f) => f.endsWith('.json') && f !== 'passages.json')) {
  questions.push(...(JSON.parse(readFileSync(join(dataDir, file), 'utf8')) as Question[]))
}

const passages = JSON.parse(
  readFileSync(join(dataDir, 'passages.json'), 'utf8'),
) as { id: string; title: string; text: string[] }[]
const passageById = new Map(passages.map((p) => [p.id, p]))

const shown = questions.filter((q) => !seen.has(q.id))

const out: string[] = []
out.push('# Question review sheet')
out.push('')
out.push(
  `${shown.length} question${shown.length === 1 ? '' : 's'}` +
    (onlyNew && seen.size > 0 ? ` (${seen.size} already reviewed and hidden)` : '') +
    '. Generated by `npm run review` — do not edit by hand.',
)
out.push('')
out.push('Options appear in the order the child sees them. The correct answer is marked **✓**.')
out.push('')
out.push('**What to look for**, since the validator cannot check these:')
out.push('')
out.push('- Could a bright child argue for a different answer?')
out.push('- Is any distractor accidentally correct, or too obviously silly?')
out.push('- Is the wording clear on first reading, and the vocabulary fair for Year 5/6?')
out.push('- Does the explanation actually teach the method, rather than restating the answer?')
out.push('- Is the difficulty label about right?')
out.push('')
out.push('Note anything doubtful by question id — the id is shown with each question.')
out.push('')

// --- Passages -------------------------------------------------------------
const usedPassages = new Set(shown.map((q) => q.passageId).filter(Boolean) as string[])
if (usedPassages.size > 0) {
  out.push('---')
  out.push('')
  out.push('## Comprehension passages')
  out.push('')
  for (const id of usedPassages) {
    const p = passageById.get(id)
    if (!p) continue
    out.push(`### ${p.title}`)
    out.push('')
    out.push(`\`${p.id}\``)
    out.push('')
    for (const para of p.text) out.push(`> ${para}`, '>')
    out.push('')
  }
}

// --- Questions ------------------------------------------------------------
const bySubject = new Map<string, Question[]>()
for (const q of shown) {
  bySubject.set(q.subject, [...(bySubject.get(q.subject) ?? []), q])
}

for (const [subject, list] of [...bySubject].sort()) {
  out.push('---')
  out.push('')
  out.push(`## ${subject} (${list.length})`)
  out.push('')

  const byTopic = new Map<string, Question[]>()
  for (const q of list) byTopic.set(q.topic, [...(byTopic.get(q.topic) ?? []), q])

  for (const [topic, tList] of [...byTopic].sort()) {
    out.push(`### ${topic} (${tList.length})`)
    out.push('')
    for (const raw of [...tList].sort((a, b) => a.difficulty - b.difficulty)) {
      const q = shuffleOptions(raw)
      out.push(
        `**${q.id}** · ${DIFFICULTY[q.difficulty] ?? q.difficulty} (${q.difficulty}) · \`${q.skill}\`` +
          (q.passageId ? ` · passage: ${q.passageId}` : '') +
          (q.verify ? ` · verified: \`${q.verify}\`` : ''),
      )
      out.push('')
      out.push(q.question)
      out.push('')
      q.options.forEach((opt, i) => {
        const mark = i === q.answer ? ' **✓**' : ''
        const note = q.distractorNotes?.[i]?.trim()
        out.push(`- ${LETTERS[i]}. ${opt}${mark}${note ? ` — *${note}*` : ''}`)
      })
      out.push('')
      out.push(`*Why:* ${q.explanation}`)
      out.push('')
      out.push(`*Remember:* ${q.learningPoint}`)
      out.push('')
    }
  }
}

writeFileSync(join(docsDir, 'review-sheet.md'), out.join('\n'), 'utf8')
console.log(`Wrote docs/review-sheet.md — ${shown.length} question(s).`)
if (!onlyNew) {
  console.log('To mark everything as reviewed, run: npm run review:accept')
}
