/**
 * Split the authored bank into the two halves the app loads separately.
 *
 *   src/data/free.json   bundled into the client, public, always available
 *   public/paid.json     fetched at runtime by src/data/index.ts
 *
 * Neither is committed — both are regenerated by `npm run split`, which runs
 * ahead of both `npm test` and `npm run build`.
 *
 * Emitting the paid half to public/ keeps the deployed app exactly as it is
 * today: the whole 434-question bank, free to everyone. It is the seam, not the
 * paywall. Closing it is two steps, once there is a backend to close it against:
 * point VITE_PAID_BANK_URL at an authenticated endpoint, and stop writing
 * PUBLIC_PAID below.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { partitionBank } from '../src/data/access'
import maths from '../src/data/maths.json'
import english from '../src/data/english.json'
import verbalReasoning from '../src/data/verbal-reasoning.json'
import nonVerbalReasoning from '../src/data/non-verbal-reasoning.json'
import generated from '../src/data/generated.json'
import type { Question } from '../src/types'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const FREE_OUT = join(root, 'src/data/free.json')
const PUBLIC_PAID = join(root, 'public/paid.json')

// Same order as src/data/index.ts concatenated them before the split.
const bank = [
  ...(maths as Question[]),
  ...(english as Question[]),
  ...(verbalReasoning as Question[]),
  ...(nonVerbalReasoning as Question[]),
  ...(generated as Question[]),
]

const { free, paid } = partitionBank(bank)

mkdirSync(dirname(PUBLIC_PAID), { recursive: true })
writeFileSync(FREE_OUT, `${JSON.stringify(free, null, 2)}\n`)
writeFileSync(PUBLIC_PAID, JSON.stringify(paid))

const pct = Math.round((free.length / bank.length) * 100)
console.log(
  `split ${bank.length} questions: ${free.length} free (${pct}%), ${paid.length} paid`,
)
